### ISSUE TITLE
Deprecate in favour of @types/yandex-maps

### ISSUE THREAD

**Issue by kachkaev** [Delagen/typings-yandex-maps#4]
I'd be nice to add a link to `@types/yandex-maps` in README.md and GitHub project description. This would save new visitors from confusion.

E.g.:

> **Warning:** This project is deprecated in favour of [@types/yandex-maps](https://www.npmjs.com/package/@types/yandex-maps) ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yandex-maps))

### Markdown for README.md

```markdown
> **Warning:** This project is deprecated in favour of [@types/yandex-maps](https://www.npmjs.com/package/@types/yandex-maps) ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yandex-maps))
```

### Raw text for project description

```markdown
Deprecated in favour of https://www.npmjs.com/package/@types/yandex-maps
```

Many thanks for crafting Yandex Maps typings!

**Comment by kachkaev** [comment]
ping @Delagen :)

**Comment by delagen** [comment]
Please make a PR, i am at holidays till 11 jan.

**Comment by kachkaev** [comment]
See #5
